project:
  type: website
  render:
    - "*.qmd"
  preview: 
    watch-inputs: true
    navigate: true
  execute-dir: project

website:
  title: "Research project template"
  navbar:
    left: 
      - text: Home
        href: index.qmd
      - text: Analysis
        href: playground/playground.qmd
    right:
      - text: Slides
        href: slides/index.qmd
      - text: Manuscript
        href: manuscripts/manuscripts.qmd
      - icon: github
        menu: 
          - text: Source Code
            href: https://github.com/Boudry-Felix/research-template
          - text: Discussion
            href: https://github.com/Boudry-Felix/research-template/discussions
          - text: Issues
            href: https://github.com/Boudry-Felix/research-template/issues

format:
  html:
    respect-user-color-scheme: true
    theme:
      dark: darkly
      light: flatly
    toc: true
    code-fold: true
    code-summary: "Show code"
    page-layout: full

execute: 
  freeze: false

knitr:
  opts_chunk: 
    fig.align: center